Eslint
Neofonie/tech-radar pull request #4
Opened 2018-06-13 10:02 UTC by MadNewjean

2018-06-13 13:08 UTC, rejas requested changes

2018-06-13 13:08 UTC, rejas commented on package.json
> +    "lint": "./node_modules/.bin/eslint docs/*.js"
wie gesagt, das node_modules/.bin ist unnötig eigentlich. siehe zeile 15, browsersync wird auch automatisch aufgelöst bzw gefunden wenn "npm run test" ausgeführt wird.

2018-06-13 13:08 UTC, rejas commented on package.json
>      "browser-sync": "^2.24.4"
ah, stimmt, kannst du meine brwoser-sync zeile runter ins devDependencies ziehen? da gehört sie eigentlich hin (ist ja zum entwickeln notendig nicht zum deployen)

2018-06-13 13:57 UTC, MadNewjean commented on package.json
> +    "lint": "./node_modules/.bin/eslint docs/*.js"
Habe das node_models/.bin entfernt.

2018-06-13 13:58 UTC, MadNewjean commented on package.json
>      "browser-sync": "^2.24.4"
Habe die Zeile " "browser-sync": "^2.24.4" zu devdependencies gezogen.

2018-06-14 08:54 UTC, rejas approved these changes

2018-06-14 08:55 UTC, merged